### ISSUE TITLE
CSS redundancy and :has() selector compatibility concerns

### ISSUE THREAD

**Issue by mryfmo** [mryfmo/obsidian-feed#17]
## Problem Overview
The CSS file contains redundant declarations and uses the `:has()` selector which may have compatibility issues with older Electron versions.

## Affected File
- `styles.css`

### 1. CSS Redundancy
Both `.fr-controls-bar` and `.fr-action-icons-group` define `gap: 0.5rem;` separately, violating DRY principle:

```css
.fr-controls-bar {
  display: flex;
  gap: 0.5rem; /* Duplicated */
  /* ... */
}

.fr-action-icons-group {
  display: flex;
  gap: 0.5rem; /* Duplicated */
  /* ... */
}
```

### 2. :has() Selector Compatibility
The CSS uses `:has()` selector which requires Chromium 105+:

```css
.fr-item-info:not(:has(.fr-item-source)) .fr-item-link {
  color: var(--text-muted);
}
```

While Obsidian's `minAppVersion: 1.8.10` likely uses Electron 26.x (Chromium 116+), this isn't explicitly verified.

### 1. Use CSS Variables for Common Values
```css
/* Define spacing variables */
:root {
  --fr-spacing-xs: 0.25rem;
  --fr-spacing-s: 0.375rem;
  --fr-spacing-m: 0.5rem;
  --fr-spacing-l: 0.75rem;
  --fr-spacing-xl: 1rem;
}

/* Apply consistently */
.fr-controls-bar,
.fr-action-icons-group {
  display: flex;
  gap: var(--fr-spacing-m);
}

/* Other components can reuse */
.fr-feeds-nav-item {
  padding: var(--fr-spacing-s) var(--fr-spacing-m);
}
```

### 2. Add Compatibility Check or Fallback
Option A - Add compatibility comment:
```css
/* :has() selector requires Chromium 105+ (Electron 23+)
   Obsidian 1.8.10 uses Electron 26.x, so this is safe */
.fr-item-info:not(:has(.fr-item-source)) .fr-item-link {
  color: var(--text-muted);
}
```

Option B - Provide JavaScript fallback:
```typescript
// If :has() not supported, add class via JavaScript
if (\!CSS.supports('selector(:has(*))')) {
  document.querySelectorAll('.fr-item-info').forEach(el => {
    if (\!el.querySelector('.fr-item-source')) {
      el.classList.add('fr-no-source');
    }
  });
}
```

```css
/* Fallback styling */
.fr-item-info.fr-no-source .fr-item-link {
  color: var(--text-muted);
}
```

### 3. Additional CSS Improvements
While addressing these issues, consider:

```css
/* Group related properties */
.fr-feeds-reader {
  /* Layout */
  display: flex;
  height: 100%;
  
  /* Spacing */
  padding: var(--fr-spacing-m);
  gap: var(--fr-spacing-l);
  
  /* Visual */
  background: var(--background-primary);
}

/* Use semantic class names */
.fr-feed-navigation { /* Instead of .fr-feeds-nav */ }
.fr-content-area { /* Instead of .fr-content */ }

/* Consider CSS Grid for layout */
.fr-feeds-reader {
  display: grid;
  grid-template-columns: 300px 1fr;
  gap: var(--fr-spacing-l);
}
```

## Priority
Low - These are maintainability and potential compatibility issues, not breaking bugs

## Benefits
- Better maintainability through DRY principle
- Easier theme customization with CSS variables
- Explicit compatibility documentation
- Consistent spacing throughout the UI
- Future-proof CSS structure
